php_pool_conf_dir: '/etc/php/{{ php_version}}/fpm/pool.d'
php_cli_conf_dir: '/etc/php/{{ php_version}}/cli'
php_fpm_conf_dir: '/etc/php/{{ php_version}}/fpm'
php_service_name: 'php{{ php_version}}-fpm'
php_fpm_sock: '/run/php/php{{ php_version}}-fpm.sock'
php_fpm_pid: '/run/php/php{{ php_version }}-fpm.pid'
web_user: 'www-data' 
php_upload_tmp: '{{ data_dir }}/upload_tmp'